services:
  - type: web
    name: backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - fromDotEnv: true

  - type: web
    name: frontend
    env: node
    rootDir: commis-next
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - fromDotEnv: true
